# Generated by Django 2.0.7 on 2018-08-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='instgram_url',
            new_name='instagram_url',
        ),
    ]
